os: linux
dist: bionic
language: csharp
mono: none
#dotnet: 6.0.100-preview.2.21155.3
solution: Covid19Api.sln

addons:
  snaps:
    - name: dotnet-sdk
      classic: true
      channel: 6.0/beta

stages:
  - build
  - invoke-deployment

jobs:
  include:
    - stage: build
      name: dotnet-build
      if: tag IS NOT present
      before_script:
        - sudo snap alias dotnet-sdk.dotnet dotnet
      script:
        - dotnet build
          
    - stage: invoke-deployment
      name: Invoke Device Deployment
      if: tag IS present
      before_script: 
        - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        - az config set extension.use_dynamic_install=yes_without_prompt
      script:
        - ./invoke-deployment.sh